"""Generic realtime task contracts and reference tasks."""

from streammuse.domain.tasks.animal_naming import AnimalNamingTask
from streammuse.domain.tasks.models import (
    ChatMessage,
    ChatModelResponse,
    DeadlineMode,
    HumanInputMode,
    HumanResponse,
    HumanResponseRequest,
    HumanResponseSource,
    HumanResponseStatus,
    InteractiveActor,
    InteractiveTask,
    InteractiveTurnRecord,
    LocalChatModel,
    RealtimeTask,
    SpeechAwareInteractiveTask,
    SpeechContext,
    SpokenResponseParseResult,
    SpokenResponseParseStatus,
    TaskRefereeResult,
    TaskState,
    TaskTurn,
)
from streammuse.domain.tasks.zip_zap_zop import ZipZapZopTask

__all__ = [
    "AnimalNamingTask",
    "ChatMessage",
    "ChatModelResponse",
    "DeadlineMode",
    "HumanInputMode",
    "HumanResponse",
    "HumanResponseRequest",
    "HumanResponseSource",
    "HumanResponseStatus",
    "InteractiveActor",
    "InteractiveTask",
    "InteractiveTurnRecord",
    "LocalChatModel",
    "RealtimeTask",
    "SpeechAwareInteractiveTask",
    "SpeechContext",
    "SpokenResponseParseResult",
    "SpokenResponseParseStatus",
    "TaskRefereeResult",
    "TaskState",
    "TaskTurn",
    "ZipZapZopTask",
]
