"""Domain contracts and prosody analysis for beat-aligned rap text."""

from streammuse.domain.rap.models import (
    AlignedLine,
    BeatSlot,
    ProsodyAnalysis,
    RapPlan,
    ScheduledSyllable,
    Syllable,
)
from streammuse.domain.rap.flow import FlowProvenance, FlowSlot, FlowTemplate, materialize_flow
from streammuse.domain.rap.generation import CandidateBatch, CandidateRequest
from streammuse.domain.rap.evaluation import CandidateEvaluation, ScoreComponent, ScoreWeights, SelectionResult
from streammuse.domain.rap.events import RapEvent, RapEventType
from streammuse.domain.rap.audio import (
    AudioFormat,
    AudioPlaybackNotice,
    AudioPlaybackNoticeKind,
    AudioPlaybackSnapshot,
    AudioWarning,
    AudioWarningCode,
    AudioWarningSeverity,
    PcmAudio,
    PlaybackState,
    PreparedRapBar,
    RenderedSyllable,
    SyllablePlacementDiagnostic,
    SyllableRenderRequest,
)
from streammuse.domain.rap.prosody import analyse_syllables, extract_words, normalize_text
from streammuse.domain.rap.scenario import RapScenario, ScenarioSegment
from streammuse.domain.rap.remote_chunk import (
    REMOTE_CHUNK_ARTIFACT_IDS,
    REMOTE_CHUNK_MONITORING_SCHEMA_VERSION,
    MAX_REMOTE_SOURCE_SECONDS,
    REMOTE_CHUNK_SCHEMA_VERSION,
    REMOTE_CHUNK_SCHEMA_VERSION_V2,
    REMOTE_CHUNK_SCHEMA_VERSIONS,
    PreparedRapChunk,
    RemoteCandidatePolicy,
    RemoteCandidateStats,
    RemoteRapBarRequest,
    RemoteRapChunkDiagnostics,
    RemoteRapChunkManifest,
    RemoteRapChunkRequest,
    RemoteRapChunkTransportAttempt,
    RemoteSelectedBar,
)

__all__ = [
    "AlignedLine",
    "AudioFormat",
    "AudioPlaybackNotice",
    "AudioPlaybackNoticeKind",
    "AudioPlaybackSnapshot",
    "AudioWarning",
    "AudioWarningCode",
    "AudioWarningSeverity",
    "BeatSlot",
    "CandidateBatch",
    "CandidateRequest",
    "CandidateEvaluation",
    "FlowProvenance",
    "FlowSlot",
    "FlowTemplate",
    "ProsodyAnalysis",
    "PcmAudio",
    "PlaybackState",
    "PreparedRapBar",
    "PreparedRapChunk",
    "RapPlan",
    "RapScenario",
    "RapEvent",
    "RapEventType",
    "REMOTE_CHUNK_ARTIFACT_IDS",
    "REMOTE_CHUNK_MONITORING_SCHEMA_VERSION",
    "MAX_REMOTE_SOURCE_SECONDS",
    "REMOTE_CHUNK_SCHEMA_VERSION",
    "REMOTE_CHUNK_SCHEMA_VERSION_V2",
    "REMOTE_CHUNK_SCHEMA_VERSIONS",
    "RemoteCandidatePolicy",
    "RemoteCandidateStats",
    "RemoteRapBarRequest",
    "RemoteRapChunkDiagnostics",
    "RemoteRapChunkManifest",
    "RemoteRapChunkRequest",
    "RemoteRapChunkTransportAttempt",
    "RemoteSelectedBar",
    "ScheduledSyllable",
    "ScenarioSegment",
    "RenderedSyllable",
    "ScoreComponent",
    "ScoreWeights",
    "SelectionResult",
    "Syllable",
    "SyllablePlacementDiagnostic",
    "SyllableRenderRequest",
    "analyse_syllables",
    "extract_words",
    "materialize_flow",
    "normalize_text",
]
